= Theoretischer Rahmen

Die Leitfrage dieser Arbeit zielt auf einen baulichen Transformationsprozess: Wie wandelt sich die Wijnhaven-Wasserkante in Rotterdam vom Arbeitshafen zum Wohnquartier, und was erzählt die bauliche Schichtung dieses Ortes über Rotterdams Umgang mit seiner Waterfront? Eine solche Frage lässt sich nicht aus dem Einzelobjekt heraus beantworten, sondern verlangt einen theoretischen Rahmen, der den Wandel der Beziehung zwischen Hafen und Stadt als Prozess fassbar macht. Dieses Kapitel entwickelt diesen Rahmen aus drei Strängen der Hafenstadtforschung. Der erste liefert mit dem Port-City-Interface (Hoyle) ein chronologisches Phasenmodell, der zweite mit Meyers Lesart der Hafenstadt als Verhandlungsraum eine prozessuale und raumbezogene Vertiefung, der dritte mit Marshall, Bruttomesso und Hein die Einsicht in die Bild- und Netzwerkdimension des Waterfront-Redevelopment. Aus der Verknüpfung der drei Stränge wird abschließend die Analyseperspektive abgeleitet, mit der die sieben Wijnhaven-Bauten im weiteren Verlauf gelesen werden.

== Das Port-City-Interface (Hoyle)

Den Ausgangspunkt bildet das Modell des port-city interface, das Hoyle (1989) als chronologische Abfolge fünf idealtypischer Stufen formuliert. Hoyle beschreibt die Schnittstelle zwischen Hafen und Stadt als eine über die Zeit veränderliche Zone, deren Gestalt sich aus dem Zusammenspiel von Technik, Ökonomie, Umwelt und Politik ergibt. In der ersten Stufe, dem primitive city-port, fallen Stadt und Hafen räumlich und funktional weitgehend zusammen. In der zweiten Stufe, dem expanding city-port, wächst der Hafen über den ursprünglichen Stadtkern hinaus. Die dritte Stufe, der modern industrial city-port, ist durch die Industrialisierung des Hafens und durch großmaßstäbliche, technisch hochgerüstete Anlagen geprägt. In der vierten Stufe, dem retreat from the waterfront, zieht sich der Hafen aufgrund veränderter Schiffsgrößen und Umschlagstechniken aus den innerstädtischen Becken zurück und hinterlässt brachfallende Kanten. Die fünfte Stufe, das redevelopment of the waterfront, beschreibt die Wiederaneignung dieser freigewordenen Flächen durch die Stadt.

Hoyle (2000) ergänzt dieses Modell später um eine sechste Phase, in der sich das Verhältnis von Hafen und Stadt von einer Konflikt- zu einer Kooperationszone wandelt und die Hafen-Stadt-Beziehung auf neuer Grundlage erneuert wird. Entscheidend ist dabei seine Beobachtung, dass eine erfolgreiche Revitalisierung der Waterfront globale ökonomische Prozesse mit der spezifischen Eigenart des Ortes verbindet. Das Modell ist damit nicht allein deskriptiv, sondern enthält ein normatives Moment: Gelungenes Redevelopment ist nicht die schematische Anwendung eines internationalen Repertoires, sondern dessen Verschränkung mit der lokalen baulichen und kulturellen Identität.

Für die vorliegende Arbeit ist Hoyles Modell aus zwei Gründen tragfähig. Erstens stellt es eine Chronologie bereit, die sich mit dem Untersuchungszeitraum von 1898 bis 2023 deckt und die einzelnen Bauten als Spuren je unterschiedlicher Phasen lesbar macht. Zweitens benennt es mit Technik, Ökonomie, Umwelt und Politik genau jene Treiber, die auch am Wijnhaven wirksam sind. Zugleich ist die Grenze des Modells zu markieren: Als Idealtypus bildet es eine glatte Abfolge ab, während sich die reale Kante als Gleichzeitigkeit und Überlagerung der Phasen darstellt. Diese Spannung zwischen linearem Modell und tatsächlicher Schichtung ist für die spätere Analyse produktiv und wird dort eigens aufgenommen.

== Die Hafenstadt als Verhandlungsraum (Meyer)

Wo Hoyle die große Linie zeichnet, vertieft Meyer (1999) die innere Logik des Transformationsprozesses. In seiner Studie City and Port deutet Meyer den Wandel der Hafenstädte als allmähliche Befreiung der Waterfronts von ihrer Industrie- und Hafenfunktion. Anders als bei Hoyle steht dabei nicht die Verschiebung der Hafengrenze im Vordergrund, sondern der öffentliche Raum, der an der Schnittstelle von großmaßstäblicher Infrastruktur und lokalem Stadtgefüge entsteht. Die Waterfront ist bei Meyer kein bloßes Restprodukt des Hafenrückzugs, sondern ein Ort, an dem die Stadt aushandelt, wie sie sich zum Wasser, zur Technik und zu ihrer eigenen Geschichte verhalten will.#footnote[Die genauen Seitenbelege zu Meyer (1999) sind in der Endfassung an der Druckausgabe zu ergänzen.]

Meyer entwickelt diese Lesart im Vergleich von vier Hafenstädten, London, Barcelona, New York und Rotterdam, die jeweils einen eigenen Typus des Umgangs mit der Waterfront verkörpern. Für Rotterdam erweist sich der wechselnde Bezug zwischen innen und außen, zwischen Stadt und Hafen als konstitutiv. Die Stadt ist nicht zur einen oder anderen Seite hin eindeutig orientiert, sondern lebt von der wiederkehrenden Neujustierung dieses Verhältnisses. Ein besonderes Gewicht erhält dabei die Flutschutz-Infrastruktur: Die Notwendigkeit, sich gegen das Wasser zu sichern, erzeugt sichtbare Trennungen im Stadtkörper, die zugleich Schwellen und Bruchstellen zwischen den Maßstäben sind.

Damit liefert Meyer der Arbeit den prozessualen und zugleich raumbezogenen Gegenpol zu Hoyles Phasenschema. Während Hoyle die Frage beantwortet, in welcher Phase ein Bau steht, beantwortet Meyer die Frage, was an der Kante konkret verhandelt wird: das Verhältnis von Infrastruktur und Stadtgefüge, von Schutz und Zugang, von Großform und Quartier. Für die Wijnhaven-Kante ist diese Perspektive zentral, weil sich der untersuchte Ort gerade nicht als reine Abfolge von Bauten, sondern als fortlaufende Aushandlung dieser Beziehung beschreiben lässt.

== Waterfront-Redevelopment als Bildproduktion (Marshall, Bruttomesso, Hein)

Der dritte Strang ergänzt die bisherigen um die Frage, was die erneuerte Waterfront darstellen soll. Marshall (2001) fasst das Waterfront-Redevelopment als eine zweite Generation, eine second generation, von Hafenstadtprojekten und rückt damit den Aspekt der städtischen Bildproduktion in den Vordergrund. Redevelopment ist für ihn nicht nur Flächenkonversion, sondern ein remaking the city image, eine bewusste Neuformung des Selbstbildes, das die Stadt nach außen und nach innen kommuniziert. Marshall ordnet das Feld entlang von vier Themen: dem Zugang zur Waterfront (connection to the waterfront), der Neuformung des Stadtbildes (remaking the city image), dem Verhältnis von Hafen und Stadt (port and city relations) sowie der besonderen Lage neuer Waterfronts in historisch gewachsenen Städten.

Diese Akzentsetzung ist für die Leitfrage unmittelbar relevant. Wenn die bauliche Schichtung am Wijnhaven etwas über Rotterdams Umgang mit seiner Waterfront erzählen soll, dann ist die ikonische Aufladung der einzelnen Bauten kein Nebeneffekt, sondern Teil des Gegenstands. Die markanten Hochpunkte und Sonderformen der jüngeren Phase lassen sich mit Marshall als Instrumente eines Stadtbild-Marketings lesen, die das industrielle Erbe der Kante in ein konsumierbares, repräsentatives Bild überführen.

Hein (2011) erweitert diese Perspektive um die translokale Dimension. Mit dem Begriff der port cityscapes beschreibt sie Hafenstädte als Knoten in netzwerkbasierten, über den einzelnen Ort hinausreichenden Beziehungsgeflechten. Die Bilder, die eine Waterfront produziert, zirkulieren in einem internationalen Vergleichsraum und stehen im Wettbewerb mit denen anderer Hafenstädte. Bruttomesso (1993) liefert dazu den europäischen Vergleichsdiskurs der frühen 1990er Jahre, in dem die Wasserkante als neue Grenze und als bevorzugtes Feld städtischer Erneuerung verhandelt wird. Beide rahmen das Geschehen am Wijnhaven als lokalen Ausschnitt einer breiteren, international geteilten Bewegung.

== Ableitung der Analyseperspektive

Aus der Zusammenführung der drei Stränge ergibt sich die Analyseperspektive dieser Arbeit. Hoyle stellt die Chronologie und die Treiber bereit, Meyer die prozessuale Logik der Aushandlung an der Kante, Marshall, Hein und Bruttomesso die Bild- und Netzwerkdimension. Die Wijnhaven-Kante wird im Folgenden als Ort gelesen, an dem diese drei Ebenen ineinandergreifen: als bauliche Schichtung von Hoyle-Phasen, als Rotterdamer Variante von Meyers Infrastruktur-Stadt-Aushandlung und als fortlaufende Produktion von Stadtbildern im Sinne Marshalls.

Konkret schlägt diese Arbeit vor, die sieben untersuchten Bauten als materielle Spuren je unterschiedlicher Hoyle-Phasen zu lesen. Diese Zuordnung ist ausdrücklich als eigene analytische Lesart zu verstehen und nicht als ein bei Hoyle belegter Befund. In dieser Lesart steht das Witte Huis für den modern industrial city-port, also für die dritte Phase des hochgerüsteten Industriehafens, dessen Selbstbewusstsein sich im ersten Hochhaus des Kontinents verdichtet. Die Kubuswoningen (1982 bis 1984, erste Präsentation 1978) markieren in dieser Lesart die Schwelle zwischen dem retreat from the waterfront und dem redevelopment, also den Übergang von der verlassenen zur wiederangeeigneten Kante. Red Apple, Markthal und CasaNova schließlich werden der sechsten Erneuerungsphase im Sinne Hoyles (2000) zugeordnet, in der die Kante endgültig zur Kooperationszone und zum Wohn- und Konsumort wird.

Diese Zuordnung erhebt nicht den Anspruch, die Bauten lückenlos in ein lineares Schema zu pressen. Im Gegenteil liegt der analytische Wert gerade in der Reibung zwischen Modell und Befund: Die reale Kante zeigt die Phasen nicht nacheinander, sondern als Gleichzeitigkeit und Überlagerung, in der ein Industriehochhaus von 1898 unmittelbar neben einem Wohnturm der 2020er Jahre steht. Eben diese Schichtung, so die leitende Annahme, erzählt mehr über Rotterdams Umgang mit seiner Waterfront als jede einzelne Phase für sich. Die folgende Analyse nutzt den hier entwickelten Rahmen daher nicht als Raster, das über den Ort gelegt wird, sondern als Werkzeug, mit dem sich die Eigenart der Wijnhaven-Kante schärfer beschreiben lässt.
