= Methodik

== Fallstudie als Forschungsdesign (Yin, Flyvbjerg)

Die vorliegende Arbeit untersucht die Wijnhaven-Wasserkante als räumlich klar umgrenzten Einzelfall. Diese Entscheidung folgt einer methodischen Überlegung: Die Transformation der Kante vom Arbeitshafen zum Wohnquartier ist kein abstrakter Prozess, sondern an einem konkreten Ort in seine bauliche Gestalt eingeschrieben. Yin (2014) begründet die Fallstudie als Methode der Wahl, wenn ein zeitgenössisches Phänomen in seinem realen Kontext untersucht wird und sich Phänomen und Kontext nicht trennscharf voneinander lösen lassen. Genau diese Lage liegt hier vor: Der Funktionswandel der Waterfront (das Phänomen) ist von Rotterdams hafenwirtschaftlicher, planerischer und stadtbaulicher Geschichte (dem Kontext) nicht abzukoppeln. Die Kante lässt sich nicht im Labor rekonstruieren, sondern nur dort lesen, wo sie steht. Die Fallstudie ist damit nicht eine Verlegenheitslösung gegenüber dem breiten Vergleich, sondern das dem Gegenstand angemessene Forschungsdesign.

Mit diesem Zuschnitt stellt sich der bekannte Einwand, aus einem einzelnen Fall lasse sich nichts verallgemeinern. Flyvbjerg (2006) zeigt jedoch, dass dieser Einwand auf einem Missverständnis beruht. Die Kraft des konkreten Beispiels werde systematisch unterschätzt: Sorgfältig gewählte Einzelfälle erlauben keine statistische, wohl aber eine analytische Erkenntnis, weil sie Zusammenhänge in einer Tiefe sichtbar machen, die der breite Querschnitt notwendig verfehlt. Für die hier verfolgte Leitfrage ist gerade diese Tiefe entscheidend. Wer verstehen will, was Rotterdams Umgang mit seiner Waterfront über mehr als ein Jahrhundert auszeichnet, gewinnt mehr aus der dichten Lesart einer einzigen, über alle Phasen hinweg bebauten Kante als aus dem oberflächlichen Vergleich vieler Hafenstädte.

Die Wijnhaven-Kante ist in diesem Sinne ein bewusst gewählter, kein beliebiger Fall. Sie versammelt auf engem Raum bauliche Schichten aus rund 125 Jahren, vom Witte Huis (1898) über die Wederopbouw- und Bürokante und die Kubuswoningen (1982 bis 1984, erste Präsentation 1978) bis zu Red Apple, Markthal und CasaNova. Diese ungewöhnliche Dichte unterschiedlicher Bauphasen an einem Ort macht den Fall zu einem aufschlussreichen, im Sinne Flyvbjergs (2006) "kritischen" Beispiel: An ihm lässt sich der Wandel des Verhältnisses von Stadt und Hafen nicht behaupten, sondern an gebauter Substanz nachweisen. Die analytische Verallgemeinerung zielt entsprechend nicht auf die Behauptung, jede Hafenstadt verfahre wie Rotterdam, sondern auf die Frage, was sich an diesem Fall über den Umgang mit Waterfronts überhaupt lernen lässt.

== Morphologisch-typologische Lesart der Kante (Conzen, Caniggia/Maffei, Moudon, Kropf)

Um die Kante als geschichtete Form lesen zu können, stützt sich die Arbeit auf die stadtmorphologische Forschungstradition. Conzen (1960) hat mit seiner historico-geographischen town-plan analysis das Instrumentarium bereitgestellt, den Stadtgrundriss in seine Elemente zu zerlegen: Straßen und ihr Netz, Parzellen und ihre Muster, Gebäude und ihre Anordnung. Entscheidend für die vorliegende Frage ist Conzens Beobachtung der Persistenz: Ältere Schichten des Grundrisses überdauern häufig die Bauten, die sie einst trugen, und prägen noch dann die Form, wenn ihre ursprüngliche Funktion längst verschwunden ist. Genau diese Persistenz ist an der Wijnhaven-Kante zu erwarten, wo der historische Hafenwasserraum die Anordnung der späteren Wohnbebauung bis heute steuert.

Während Conzen vom Grundriss her argumentiert, setzen Caniggia und Maffei (2001) am Bauwerk an. Ihre typo-morphologische Lesart fragt nach dem basic building und nach den Bautypen, aus denen sich das städtische Gewebe zusammensetzt, und nach deren Wandel über die Zeit. Für die Kante bedeutet das, die einzelnen Bauten nicht nur als Objekte, sondern als Vertreter von Typen zu verstehen: das bürgerliche Kontor- und Geschäftshaus des späten 19. Jahrhunderts, der Wederopbouw-Büroblock, das experimentelle Wohnhaus der Kubuswoningen, der Wohnturm der jüngsten Phase. Moudon (1997) begründet das Feld der urban morphology als interdisziplinäres Unternehmen und verbindet die verschiedenen Schulen, während Kropf (2017) das Begriffsgebäude systematisiert und es für die konkrete Analyse handhabbar macht. Beide stützen den Anspruch, die Kante nicht impressionistisch, sondern mit einem geordneten Vokabular zu beschreiben.

Diese morphologisch-typologische Lesart trägt unmittelbar das in dieser Arbeit gewählte Vorgehen entlang eines Transekts durch die Kante. Es ist die eigene analytische Entscheidung dieser Arbeit, die Wijnhaven-Wasserkante als geschichtete Form zu behandeln, in der ältere Schichten neben jüngeren fortbestehen, statt von ihnen abgelöst zu werden. Der Transekt schneidet diese Schichtung quer an und macht sie als Abfolge lesbar. Die morphologische Tradition liefert dafür die Begründung: Wenn Form Geschichte speichert, dann ist die bauliche Schichtung der Kante selbst die Quelle, aus der sich Rotterdams wechselnder Umgang mit seiner Waterfront rekonstruieren lässt. Die spätere Zuordnung einzelner Bauten zu den Phasen des Hoyle-Modells ist dabei als eigene interpretierende Lesart zu verstehen und wird im Folgenden als solche kenntlich gemacht, nicht als gesicherte Tatsache ausgegeben.

== Plan- und Dokumentenanalyse und Vor-Ort-Begehung (Lynch, Kostof)

Die morphologische Lesart wird durch zwei einander ergänzende Zugänge ins Werk gesetzt: die Analyse von Plänen und Dokumenten sowie die Begehung des Ortes. Die Plan- und Dokumentenanalyse bildet die dokumentarische Grundlage. Sie wertet historische und aktuelle Stadtpläne, Katasterunterlagen, Erbe- und Planungsdokumente sowie Architektenmonografien aus, um die bauliche Entwicklung der Kante über den Untersuchungszeitraum von 1898 bis 2023 zu rekonstruieren. Diese Quellen erlauben es, die Schichtung der Kante zeitlich zu ordnen und die einzelnen Bauphasen datierend und maßlich zu fassen.

Die dokumentarisch gewonnenen Befunde bleiben jedoch unvollständig, solange sie nicht am Ort selbst geprüft werden. Hier setzt die Vor-Ort-Begehung im Rahmen der Exkursion an, die theoretisch durch Lynch (1960) und Kostof (1992) begründet ist. Lynch (1960) liefert mit dem Image of the City das Vokabular der beobachtenden Wahrnehmung: Die Kante (edge) ist bei ihm eines der grundlegenden Elemente, mit denen sich Menschen ein Bild der Stadt machen, und die imageability eines Ortes lässt sich nicht aus dem Plan, sondern nur in der räumlichen Erfahrung erschließen. Die Wasserkante ist in Lynchs Sinne eine paradigmatische edge, eine Grenzlinie, an der zwei Bereiche aufeinandertreffen. Kostof (1992) wiederum behandelt in The City Assembled die city edge und die Waterfront ausdrücklich als eigenständiges städtebauliches Thema und liefert damit die historische Tiefenschärfe für die Lesart der Rotterdamer Kante.

Die Begehung versteht sich nicht als bloße Illustration der Schreibtischarbeit, sondern als eigenständiger, prüfender Schritt. Was in Plänen und Datenbanken als Datum erscheint, wird vor Ort auf seine räumliche Wirkung hin befragt: wie die Bauten der verschiedenen Phasen tatsächlich aneinanderstoßen, wie die Kante als Schwelle zwischen Wasser und Stadt erfahrbar ist, wo die dokumentierte Schichtung im gebauten Raum sichtbar wird und wo nicht. Damit ist die beobachtende, bildbezogene Begehung der dokumentarischen Analyse nicht nach-, sondern beigeordnet: Beide Zugänge korrigieren und ergänzen einander und sichern so die Befunde, auf denen die Argumentation der Arbeit aufbaut.

== Quellenlage und Quellenkritik

Die Quellenlage zur Wijnhaven-Kante ist heterogen und verlangt einen entsprechend differenzierten kritischen Umgang. Die ausgewerteten Materialien lassen sich grob drei Gruppen zuordnen: erstens amtliche Erbe- und Planungsdokumente, etwa die Eintragungen der Rijksdienst voor het Cultureel Erfgoed (RCE) zum Witte Huis als Rijksmonument oder die städtischen Planungsunterlagen der Gemeente Rotterdam (2007, 2019); zweitens Architektenmonografien und Werkdarstellungen, etwa zur Red Apple (Groenendijk, Christiaanse, Brouwers 2009) oder zu den Kubuswoningen (Hengeveld 2008); drittens Fachdatenbanken zur Hochbaudokumentation wie das Skyscraper Center des CTBUH. Jede dieser Gruppen hat eigene Stärken und eigene blinde Flecken: Amtliche Dokumente sind verlässlich in der rechtlichen und denkmalpflegerischen Einordnung, oft aber knapp in technischen Kennzahlen; Monografien sind detailreich, aber nicht selten dem Werk und seinen Urhebern verpflichtet; Datenbanken bieten standardisierte Kennzahlen, deren Herkunft jedoch nicht immer transparent ist.

Aus dieser Heterogenität ergeben sich an mehreren Stellen Diskrepanzen, die transparent zu machen sind, statt sie zu glätten. Beim Witte Huis nennt die RCE zehn Geschosse, aber keine Meterzahl; die häufig kursierende Höhe von rund 43 m ist eine Sekundärangabe und wird hier entsprechend vorsichtig geführt. Beim EY-Turm an den Boompjes 258 lässt sich die exakte Höhe nicht aus der Hochbau-Datenbank sichern. Bei der Red Apple divergiert die Zahl der Wohnungen zwischen den Sekundärquellen, weshalb hier den verbindlicheren Angaben aus Groenendijk, Christiaanse und Brouwers (2009) der Vorzug gegeben wird. Die CasaNova erreichte ihren Hochpunkt im Dezember 2021 und wurde am 1. Dezember 2022 übergeben; sie wird daher als Bau der Jahre 2022/2023 geführt. Besondere Sorgfalt verlangt die Volumenregel des Masterplans: Ein TU-Delft-Beleg (Mak 2011) nennt 22 m³/m² und eine maximale Turmgrundfläche von 580 m², während KCAP teils von rund 35 m³/m² spricht. Im Folgenden wird die Angabe von 22 m³/m² verwendet; die abweichende KCAP-Angabe wird transparent erwähnt, aber nicht mit ihr vermischt.

Dieser Umgang mit den Quellen ist nicht bloße Sorgfaltspflicht, sondern methodisch konsequent. Wo die Dokumente einander widersprechen, wird der Widerspruch ausgewiesen und die belastbarere Angabe begründet bevorzugt, nicht eine Scheinpräzision erzeugt. Hier schließt sich der Kreis zur Begehung: Die Vor-Ort-Wahrnehmung dient nicht zuletzt der Prüfung der dokumentarisch gewonnenen Befunde. Wo sich maßliche oder datierende Angaben nicht eindeutig sichern lassen, kann die räumliche Erfahrung zumindest die Größenordnung und die bauliche Wirkung verifizieren und so die dokumentarische Unsicherheit einhegen. Die Verschränkung von Plananalyse, Dokumentenkritik und Begehung ist damit nicht nur ein Nebeneinander dreier Methoden, sondern ein abgestimmtes Verfahren, das die Verlässlichkeit der Befunde sichert, auf denen die Beantwortung der Leitfrage beruht.
