= Rotterdams Umgang mit seiner Waterfront

Die Transformation der Wijnhaven-Kante lässt sich nur verstehen, wenn man sie in die längere Geschichte des Rotterdamer Umgangs mit seiner Wasserkante einbettet. Das vorliegende Kapitel rekonstruiert diese Geschichte als Abfolge von Konfigurationen, in denen sich das Verhältnis von Stadt und Wasser jeweils neu bestimmt: vom dicht bebauten Hafen- und Geschäftsviertel des Maritiem District über die radikale Zäsur der Bombardierung 1940 und den funktionsgetrennten Wiederaufbau bis zu den gestaffelten Wellen einer programmatischen Rückwendung zum Fluss seit den 1980er Jahren. Die Leitfrage, was diese bauliche Schichtung über Rotterdams Umgang mit seiner Waterfront erzählt, wird damit auf der Ebene der stadtweiten Steuerung verankert, bevor sie im Folgekapitel an den einzelnen Bauten der Wijnhaven-Kante konkretisiert wird. Der Wijnhaveneiland-Masterplan erscheint dabei nicht als isoliertes Entwurfsprojekt, sondern als vorläufiger Endpunkt einer langen Lernkurve im Umgang mit der eigenen Kante.

== Das Maritiem District vom 17. Jahrhundert bis 1940

Der heute als Maritiem District oder Wijnhavenkwartier bezeichnete Stadtteil entstand im frühen 17. Jahrhundert als planmäßige Hafenerweiterung der mittelalterlichen Stadt. Mit dem Leuvehaven (1609) sowie dem Wijnhaven und der Scheepmakershaven (beide 1613) wurde ein System rechteckiger, gegrabener Hafenbecken angelegt, das die Stadt zur Maas hin öffnete und zugleich ordnete (Stadsarchief Rotterdam o. J.). Diese frühe Anlage ist für die Leitfrage von grundlegender Bedeutung: Die Wijnhaven-Kante war von Anfang an eine gebaute, vermessene und ökonomisch programmierte Kante, kein natürliches Ufer. Das Wasser diente hier nicht der Anschauung, sondern dem Umschlag; die Kaikante war Arbeitsfläche.

Im Laufe der folgenden Jahrhunderte verdichtete sich das Viertel zu einem Kaufmanns- und Geschäftsquartier, in dem sich Lagerhäuser, Kontore, Banken und Handelshäuser entlang der Becken reihten. Die enge Verzahnung von Wasser, Lager und Büro prägte den Charakter der Waterstad: ein Stadtraum, dessen ökonomische Logik unmittelbar an der Kaikante ablesbar war. Gegen Ende des 19. und zu Beginn des 20. Jahrhunderts trat mit dem Witte Huis (1898) ein Hochbau hinzu, der diese kommerzielle Verdichtung sinnbildlich überhöhte. Mit seinen zehn Geschossen galt es als eines der frühen Hochhäuser Europas (RCE, Rijksmonument 334003); die häufig kursierende Höhenangabe von rund 43 m ist allerdings eine Sekundärangabe und nicht durch die Denkmaldokumentation gesichert, die lediglich die Geschosszahl benennt.

In der Terminologie Hoyles lässt sich dieser Zustand der Waterstad als modern industrial city-port lesen, in dem Stadt und Hafen funktional und räumlich noch eng ineinandergreifen (Hoyle 1989). Es handelt sich dabei um eine eigene analytische Lesart, die das Witte Huis als baulichen Zeugen dieser Phase deutet: Hochbau, Hafenbecken und Handel bilden hier eine ungetrennte Einheit. Diese Einheit zerbrach abrupt. Die deutsche Bombardierung vom 14. Mai 1940 zerstörte das Viertel nahezu vollständig; im Wijnhavengebiet überstanden nur die Regentessebrug und das Gebäude von R. Mees die Feuersbrunst (Stadsarchief Rotterdam o. J.; Wederopbouw Rotterdam o. J.). Mit der gewachsenen Schichtung von dreieinhalb Jahrhunderten verschwand zugleich die selbstverständliche Kontinuität der bebauten Kante; was an ihre Stelle treten sollte, wurde damit zu einer planerischen Entscheidung.

== Zerstörung 1940 und der Basisplan von Van Traa (1946)

Die Bombardierung hinterließ im Stadtzentrum eine weitgehend leergeräumte Fläche und stellte Rotterdam vor die Aufgabe, seine Innenstadt grundsätzlich neu zu denken. An die Stelle des noch während des Krieges erarbeiteten, dreidimensional durchgestalteten Witteveen-Plans trat der Basisplan von Cornelis van Traa, der am 28. Mai 1946 angenommen wurde (Wederopbouw Rotterdam o. J.). Der entscheidende Unterschied lag in der Methode: Wo Witteveen eine ausformulierte räumliche Gestalt vorgab, beschränkte sich der Basisplan auf einen flexiblen Rechtsrahmen, der Funktionen, Achsen und Baufelder festlegte, die konkrete Bebauung jedoch offenließ (Wederopbouw Rotterdam o. J.). Schon hier zeigt sich ein Steuerungsprinzip, das für den späteren Wijnhaveneiland-Masterplan kennzeichnend werden sollte: nicht die Form, sondern die Regel als eigentliches Planungsinstrument.

Inhaltlich folgte der Basisplan dem Leitbild der funktionsgetrennten Stadt. Die Innenstadt wurde für Handel, Verwaltung und Verkehr reserviert, das Wohnen an den Stadtrand verlagert. Breite Achsen ordneten das neue Zentrum; der Coolsingel etwa wurde von 44 auf 80 m verbreitert (Wederopbouw Rotterdam o. J.). Für das Verhältnis von Stadt und Wasser ist eine bewusste gestalterische Setzung von besonderem Interesse: Der Plan suchte den Kontrast zwischen der Weite der Maas und einer hohen, rhythmisch gegliederten Uferbebauung und sah am Leuvehaven ausdrücklich ein "Fenster zum Fluss" vor (Wederopbouw Rotterdam o. J.). Das Wasser wird hier also nicht ignoriert, aber es wird zum Gegenüber, zur Aussicht, nicht mehr zur Arbeitsfläche.

Für das Wijnhavengebiet bedeutete der Basisplan eine eindeutige Zweckbestimmung: Es wurde für Büros und Geschäftsbauten des Schifffahrtssektors vorgesehen und entwickelte sich bis Anfang der 1960er Jahre zu einem nahezu reinen Büroquartier ohne Wohnnutzung (Wederopbouw Rotterdam o. J.; Gemeente Rotterdam 2007). Mit Hoyle gelesen, markiert dieser Zustand den Beginn eines retreat from the waterfront: Der Hafenbetrieb wandert mit der Containerisierung flussabwärts ab, und die alte Kante wird zu einer monofunktionalen Büroadresse, die dem Wasser den Rücken kehrt (Hoyle 1989). Diese Zuordnung ist als eigene analytische Lesart zu verstehen; sie erklärt jedoch, warum die spätere Rückwendung zum Wasser überhaupt als planerische Aufgabe formuliert werden musste. Die funktionsgetrennte, wohnungslose Bürokante des Wiederaufbaus war der Ausgangszustand, gegen den die folgenden Wellen der Hinwendung anarbeiteten.

== Wellen der Hinwendung zum Wasser: Waterstad, Kop van Zuid, Stadsvisie 2030

Die Rückwendung Rotterdams zu seiner Wasserkante vollzog sich nicht in einem einzigen Akt, sondern in mehreren, zeitlich gestaffelten Wellen, die sich in ihrer räumlichen Reichweite und programmatischen Ambition steigerten. Eine erste Welle setzte mit dem Binnenstadsplan von 1985 ein, der unter dem Stichwort Waterstad die alten Hafenbecken des Stadtzentrums wieder ins öffentliche Bewusstsein rückte. Die Boompjes wurden als Uferboulevard neu gefasst, und am Leuvehaven entstand mit dem Maritiem Museum ein kulturell programmierter Ort am Wasser (Gemeente Rotterdam 2007). Charakteristisch für diese erste Welle ist, dass sie das Wasser zunächst vor allem als Kulisse und Freizeitraum entdeckte, ohne die monofunktionale Struktur der angrenzenden Quartiere grundlegend anzutasten.

Eine zweite, ungleich größere Welle bildete der Kop van Zuid, dessen Masterplan im September 1991 vorgelegt wurde. Unter dem Schlagwort "Manhattan aan de Maas" wurde das bis dahin abgehängte Südufer als neuer Stadtteil entwickelt und über die Erasmusbrücke an das Zentrum angebunden (Meyer 1999). Der konzeptionelle Kern lag darin, die Maas nicht länger als trennende Grenze, sondern als verbindende Mitte einer Stadt auf beiden Ufern zu begreifen. Damit kehrte sich die Logik des Wiederaufbaus um: Der Fluss wurde vom Rücken der Stadt zu ihrem Zentrum. Empirisch ist bemerkenswert, dass Doucet u. a. (2011) am Kop van Zuid eine überraschend positive Wahrnehmung durch die Bewohnerschaft feststellen, was die gängige Kritik an solchen Waterfront-Großprojekten als reine Prestigeobjekte zumindest differenziert.

Eine dritte Welle erfasste schließlich das Maritiem District selbst. Mit der am 29. November 2007 angenommenen Stadsvisie Rotterdam 2030 wurde das alte Büroquartier programmatisch zum Wohngebiet umdeklariert (Gemeente Rotterdam 2007; Gemeente Rotterdam 2019). Erst diese dritte Welle traf damit unmittelbar die Wijnhaven-Kante und machte aus der wohnungslosen Bürozeile des Wiederaufbaus ein künftiges Wohnquartier. In der Lesart Hoyles lässt sich diese Abfolge als Bewegung von redevelopment hin zu einer regelrechten Erneuerung der Beziehung von Stadt und Wasser deuten, wie sie Hoyle (2000) als sechste, jüngste Phase des Waterfront-Wandels beschreibt. Diese phasenbezogene Zuordnung ist eine eigene analytische Lesart; sie macht jedoch deutlich, dass die bauliche Verdichtung der Wijnhaven-Kante, die das folgende Kapitel untersucht, das räumliche Ergebnis einer über zwei Jahrzehnte gestaffelten politischen Programmatik ist und nicht das Werk eines einzelnen Entwurfs.

== Der Wijnhaveneiland-Masterplan als regelbasiertes Modell (KCAP, Lehnerer)

Das planerische Instrument, mit dem die programmatische Hinwendung zum Wasser auf dem Wijnhaveneiland baulich umgesetzt wurde, ist der von Kees Christiaanse und KCAP zwischen 1992/1993 und 2002 entwickelte Masterplan. Sein Wesensmerkmal ist, dass er gerade kein formfixierter Plan im Sinne Witteveens ist, sondern ein dynamisches, regelbasiertes Transformationsmodell, das die künftige Gestalt des Quartiers nicht zeichnet, sondern über Spielregeln steuert (Christiaanse 2013). Damit knüpft er, wie oben gezeigt, methodisch an die Logik des Basisplans an und treibt sie zugleich auf eine neue Stufe der Differenzierung. Die Kernregel des Plans lautet, dass ein Turm umso schlanker ausfallen muss, je höher er gebaut wird ("hoe hoger men wil bouwen, hoe slanker de toren"); Höhe wird also nicht verboten, sondern an eine Bedingung geknüpft (Christiaanse 2013).

Quantitativ lässt sich dieses Regelwerk präzise fassen. Nach der Aufarbeitung von Mak (2011) gelten ein maximales Bauvolumen von 22 m³ je m² Grundfläche, eine maximale Turmgrundfläche von 580 m², ein Turm je 2000 m² erworbener Grundfläche sowie eine maximale Diagonale eines Turms von der Wurzel der Grundfläche multipliziert mit 1,45. Hinzu treten qualitative Regeln, die Besonnung und Tageslicht auf Straßenniveau sichern, die Verschattung begrenzen und Sichtbeziehungen zur Maas schützen (Mak 2011). Auf eine Abweichung in den Quellen ist hinzuweisen: Während Mak (2011) das Maß von 22 m³/m² nennt, gibt KCAP teilweise eine größere Dichte von rund 35 m³/m² an; diese Angaben sollten nicht vermischt werden, und die vorliegende Arbeit folgt der niedrigeren, durch die TU-Delft-Aufarbeitung belegten Zahl. Für das insgesamt rund 3,9 ha große Gebiet ergibt sich eine FSI von 3,9, im Hochbau bis 6,2 (Mak 2011).

Die räumliche Folge dieses Regelwerks ist eine Gruppe schlanker, voneinander abgesetzter Türme, zwischen denen Durchblicke zur Maas erhalten bleiben. Die Blockränder werden bis zu einer Höhe von etwa 20 m bewahrt, sodass sich die Hochpunkte aus einem zusammenhängenden städtischen Sockel entwickeln; die frühere Kai-Parkierung wird durch Wandelpromenaden ersetzt, die das Ufer öffentlich begehbar machen (Christiaanse 2013). Damit übersetzt der Plan die qualitativen Ziele der Stadsvisie, also Wohnen, Besonnung und Wasserbezug, in eine geometrische Steuerungslogik. Die Wijnhaven-Kante wird nicht entworfen, sondern programmiert: Nicht ein Bild der künftigen Stadt wird festgelegt, sondern der Möglichkeitsraum, innerhalb dessen einzelne Bauten entstehen dürfen.

Theoretisch lässt sich dieses Vorgehen mit Lehnerer (2009) fassen, dessen an der ETH entstandene und bei nai010 veröffentlichte Untersuchung die regelbasierte Steuerung von Stadt als Bewegung zwischen Kontrolle und Laissez-faire beschreibt, wobei Christiaanse als Gutachter dieser Arbeit zugleich Theorie und Praxis verbindet. Christiaanse selbst (2013) charakterisiert den Wijnhaveneiland-Plan als zeitlich und räumlich offen, getragen von "flexiblen Spielregeln" und stehend in der Tradition zonenbasierter Regulierung, wie sie das New Yorker Zoning entwickelt hat; in seinem Konzept der "Open City" wird diese Offenheit zum eigentlichen städtebaulichen Programm. Damit beantwortet der Masterplan die Leitfrage auf der Ebene der Steuerung: Rotterdams Umgang mit seiner Waterfront hat sich vom dreidimensionalen Gestaltplan über den funktionstrennenden Rechtsrahmen zu einem qualitativ gesteuerten Regelmodell entwickelt, das Dichte und Höhe zulässt, ohne den öffentlichen Wasserbezug preiszugeben. Die bauliche Schichtung der Wijnhaven-Kante, die das folgende Kapitel an den einzelnen Bauten liest, ist somit das sichtbare Ergebnis eines Planungsverständnisses, das die Kante nicht ein für alle Mal festschreibt, sondern sie als dauerhaft transformierbares Gefüge begreift.
