= Die sieben Bauten als Schichtung der Kante

== Witte Huis (1898): früher Hochbau am Arbeitshafen

Das Witte Huis, entworfen von W. Molenbroek und 1897 bis 1898 errichtet, steht an der Ecke des Wijnhavens und markiert den frühesten Hochbau der hier untersuchten Reihe (RCE o. J.). Die Rijksdienst voor het Cultureel Erfgoed führt das Gebäude als Rijksmonument (Nr. 334003, designiert am 14. Mai 1986) und beschreibt es als eines der höchsten und ältesten Büroskelett-Hochhäuser (wolkenkrabbers) Europas, dessen markante Situierung auf dem Eckpunkt am Wasser ausdrücklich hervorgehoben wird (RCE o. J.; Boddaert 1998). Die RCE nennt zehn Geschosse, jedoch keine gesicherte Meterzahl; die häufig kursierende Höhe von rund 43 m ist eine Sekundärangabe und sollte daher mit Vorbehalt geführt werden.

Position und Typus des Baus sind für die Leitfrage aufschlussreich. Das Witte Huis ist kein Wohnbau, sondern ein Kontor- und Büroskelett, das unmittelbar an der arbeitenden Hafenkante steht. Es übersetzt die ökonomische Verdichtung des späten neunzehnten Jahrhunderts, in der Handel, Reederei und Umschlag die Wijnhaven-Kante prägten, in eine vertikale Hochbau-Geste. Die Kante diente hier der Logistik und dem Geschäft am Wasser; der Hochbau ist Ausdruck eben dieser produktiven Hafenfunktion und nicht ihrer Verdrängung. In Meyers Lesart der Rotterdamer Hafenstadt artikuliert sich an solchen frühen Solitären das enge Nebeneinander von Stadt und arbeitendem Hafen (Meyer 1999).

In der hier vertretenen analytischen Lesart der Phasen Hoyles wird das Witte Huis der "modern industrial city-port" zugeordnet (Hoyle 1989). Diese Zuordnung ist eine interpretierende Setzung, keine belegte Tatsache: Das Gebäude steht für den Moment, in dem Stadt und Hafen räumlich und funktional noch eng verzahnt sind und der Hochbau die Intensität der Hafenökonomie repräsentiert, bevor später der Rückzug vom Wasser einsetzt. Als Auftakt der Schichtung verankert es die Kante in ihrer industriellen Ursprungsfunktion und bildet den Bezugspunkt, gegen den sich alle späteren Transformationen lesen lassen.

== Kubuswoningen / Blaakoverbouwing (1982 bis 1984): Wohnen über der Infrastruktur

Die Kubuswoningen, von Piet Blom entworfen und 1982 bis 1984 (erste Präsentation 1978) als Blaakoverbouwing errichtet, gehören dem niederländischen Strukturalismus an, der mit Namen wie Aldo van Eyck und Herman Hertzberger verbunden ist (Hengeveld 2008). Die gekippten Würfel, die Blom als Pfahl- oder Baumdorf konzipierte, sitzen auf Pfeilern über der Straße und der darunterliegenden Verkehrsinfrastruktur. Damit entsteht ein Wohnen, das die Infrastruktur nicht verdrängt, sondern überbaut und so eine bewohnte Brücke über die bewegte Stadtkante legt.

Die Position dieses Ensembles an der Blaak, am inneren Rand der Wijnhaven-Situation, zeigt eine Transformation des Kantenverständnisses. Wo das Witte Huis noch die arbeitende Hafenkante besetzt, fügt die Blaakoverbouwing dem Ort eine Wohnschicht hinzu, die programmatisch auf die Trennung von Verkehr und Aufenthalt reagiert. Die gehobenen Wohnwürfel schaffen oben einen begehbaren Wohnhof und geben unten den Verkehr frei; die Kante wird hier zum ersten Mal in der Reihe ausdrücklich als Ort des Wohnens und nicht des Umschlags gedacht. Damit dokumentiert der Bau den Beginn einer Umwidmung, in der die innerstädtische Wasserkante ihre rein logistische Bestimmung verliert.

In der hier vertretenen Hoyle-Lesart werden die Kubuswoningen an der Schwelle zwischen "retreat from the waterfront" und "redevelopment" verortet (Hoyle 1989). Diese Einordnung ist ausdrücklich als analytische Setzung zu verstehen: Der Bau ist Symptom des Rückzugs der alten Hafenfunktionen und zugleich ein frühes Zeichen der Wiederaneignung der Kante für städtisches Wohnen. Er steht im Übergang, weil er die infrastrukturelle Vergangenheit des Ortes noch sichtbar trägt und sie gleichzeitig mit einer neuen, wohnlichen Nutzung überschreibt. So wird die Blaakoverbouwing zum Scharnier der Schichtung, an dem sich der Funktionswechsel der Kante erstmals baulich ablesen lässt.

== Bijbank der Nederlandsche Bank (1950 bis 1955) und EY-Turm Boompjes 258 (2005): die Wederopbouw- und Bürokante

Die Bijbank der Nederlandsche Bank, entworfen von H. T. Zwiers, wurde mit dem ersten Pfahl am 20. September 1950 begonnen und im Oktober 1955 eröffnet; sie steht seit 1991 unter Denkmalschutz und wurde 2016 als De Nieuwe Boompjes durch das Büro 01-10 wiedereröffnet (Wederopbouw Rotterdam o. J.). Der Bau gehört der Wederopbouw an, dem Wiederaufbau nach der Zerstörung des Rotterdamer Zentrums, und bildet damit eine denkmalgeschützte Schicht der Kante, die den ökonomischen und institutionellen Neuanfang der Nachkriegszeit verkörpert. An der Boompjes-Kante, der zum Maas gewandten Front, manifestiert sich hier nicht mehr der Umschlag, sondern die verwaltende und finanzielle Funktion der wiederaufgebauten Stadt.

Ein halbes Jahrhundert später setzt der EY-Turm Boompjes 258 diese Bürokante fort. Der Entwurf stammt von Philip Johnson und Alan Ritchie, die Ausführung lag bei 01-10 (Eentien o. J.), die Fertigstellung erfolgte 2005 (Eentien o. J.; Goldberger u. a. 2002). Die genaue Höhe des Turms ist aus der Hochbau-Datenbank nicht gesichert und wird daher hier nicht präzise angegeben. Als zurückhaltende Bürokante reiht sich der Bau in die institutionelle Front entlang der Boompjes ein und zeigt, dass die Maas-Kante über Jahrzehnte hinweg ein Ort der Verwaltung und des Büros blieb, bevor das Wohnen die Silhouette des Wijnhaveneilands dominierte.

In der hier vertretenen Hoyle-Lesart werden die Wederopbouw- und Bürokante, also Bijbank und EY-Turm gemeinsam, als Schwelle zwischen "retreat from the waterfront" und "redevelopment" gefasst (Hoyle 1989). Diese Zuordnung ist eine analytische Setzung und keine belegte Tatsache. Beide Bauten markieren den Rückzug der eigentlichen Hafenfunktion vom Wasser und zugleich die Neubesetzung der Kante mit städtischen Büro- und Verwaltungsnutzungen, die der späteren wohnlichen Wiederentwicklung vorausgehen. Die denkmalgeschützte Bijbank hält dabei die Nachkriegsschicht im Stadtbild präsent, während der EY-Turm zeigt, wie diese Bürologik bis in die Gegenwart fortgeschrieben wurde, ehe der Masterplan die Kante zur Wohnsilhouette umdeutete.

== Red Apple (2009): Auftakt des Wijnhaveneilands

Der Red Apple, 2009 fertiggestellt, wurde vom Büro KCAP unter dem Projektarchitekten Rob Hoekstra entworfen, das Interieur stammt von Jan des Bouvrie (Groenendijk/Christiaanse/Brouwers 2009). Mit rund 124 m und etwa 40 Geschossen steht der Wohnturm am Ostkopf des Wijnhaveneilands und bildet den städtebaulichen Auftakt des Eilands (CTBUH). Die Zahl der Wohnungen divergiert in den Sekundärquellen; verbindliche Angaben sind aus Groenendijk/Christiaanse/Brouwers 2009 beziehungsweise von KCAP zu beziehen, weshalb hier auf eine exakte Nennung verzichtet wird.

Die Position des Red Apple ist programmatisch aufgeladen. Als erster Hochpunkt des neu entwickelten Wijnhaveneilands ist er das direkte Ergebnis des Masterplan-Regelwerks, das die schlanke, vertikale Bebauung der Kante steuert. Das diesem Plan zugrunde liegende Konzept lässt sich als regelbasiertes Modell beschreiben, das Volumen und Hochpunkte über feste Kennzahlen verteilt (Lehnerer 2009; Christiaanse 2013). Die TU-Delft-Quelle beziffert die Volumenregel auf 22 m³ pro m² Grundstücksfläche bei einer maximalen Turmgrundfläche von 580 m² (Mak 2011); KCAP nennt an anderer Stelle teils rund 35 m³ pro m², was hier transparent erwähnt, aber nicht mit der erstgenannten Angabe vermischt wird. Der Red Apple übersetzt dieses Regelwerk in den ersten realisierten Baustein und macht das Wohnen am Wasser zum strukturierenden Prinzip der Kante.

In der hier vertretenen analytischen Lesart wird der Red Apple der sechsten Erneuerungsphase Hoyles zugeordnet (Hoyle 2000). Diese Zuordnung ist als interpretierende Setzung zu verstehen. Der Bau steht für den Moment, in dem die Kante nicht mehr nur vom Hafen zurückweicht, sondern aktiv und regelhaft als Wohnstandort zurückgewonnen wird. Als Auftakt des Wijnhaveneilands eröffnet er die jüngste Schicht der Transformation, in der die Waterfront planmäßig zum Wohnquartier umgebaut wird, und setzt den Maßstab für die nachfolgenden Bauten der Kante.

== Markthal (2014): Hybrid aus Markt, Wohnen und Parken

Die Markthal, von MVRDV im Auftrag von Provast zwischen 2004 und 2014 errichtet, ist ein bewohnter Bogen, der Markt, Wohnen und Parken in einem einzigen Baukörper verschränkt (MVRDV o. J.; Avermaete u. a. 2015). Rund 228 Wohnungen spannen sich als hufeisenförmiger Bogen über eine etwa 40 m hohe Halle, in der sich rund 96 Markt- und Ladenstände befinden; darunter liegen etwa 1.200 Tiefgaragenplätze. Das Deckenbild Hoorn des Overvloeds (Cornucopia) von Arno Coenen und Iris Roskam überzieht mit über 11.000 m² die Innenwölbung des Bogens und macht die Halle zu einem öffentlichen Innenraum von eigener Prägung (BKOR o. J.).

Die städtebauliche Bedeutung der Markthal liegt in ihrer programmatischen Dichte an der Kante. Wo die frühen Bauten je eine Funktion verkörperten, der Umschlag, das Wohnen oder das Büro, führt die Markthal Versorgung, Wohnen und Parken in einem Hybrid zusammen. Sie verbindet die öffentliche Erdgeschosszone mit dem privaten Wohnen darüber und bindet die Tiefgarage als infrastrukturelle Basis ein. Damit reagiert der Bau auf die Forderung nach einer aktiven, durchmischten Erdgeschossnutzung, die die Kante belebt und sie vom bloßen Verkehrs- und Bürostandort zum bewohnten und besuchten Stadtort wandelt (Karssenberg u. a. 2016; Gehl 2010). Die Markthal verdichtet so das Programm der Waterfront und macht die Mischung der Nutzungen selbst zum architektonischen Thema.

In der hier vertretenen Hoyle-Lesart zählt die Markthal zur sechsten Erneuerungsphase (Hoyle 2000); diese Zuordnung ist ausdrücklich als analytische Setzung zu verstehen. Der Bau steht für die reife Phase der Wiederentwicklung, in der die Kante nicht nur bewohnt, sondern als hybrider öffentlicher Ort inszeniert wird. Er führt die mit dem Red Apple begonnene Rückgewinnung der Waterfront fort und erweitert sie um die Dimension des durchmischten, öffentlich zugänglichen Programms. In der Schichtung der Kante steht die Markthal damit für den Schritt vom reinen Wohnturm zum nutzungsgemischten Hybrid.

== CasaNova (2022/2023): die jüngste Wohn-Erneuerung

CasaNova, entworfen von Barcode Architects, ist Rotterdams erster dreieckiger Wohnturm; mit 110 m und 35 Geschossen bildet er im Verbund mit dem Nachbarturm The Muse, mit dem er gemeinsame Dachgärten teilt, die jüngste Wohnschicht der Kante (Barcode Architects o. J.). Der Hochpunkt wurde im Dezember 2021 erreicht, die Übergabe erfolgte am 1. Dezember 2022; der Bau wird hier daher als 2022/2023 geführt. Mit seiner dreieckigen Grundfigur reagiert der Turm auf die beengte Parzelle des Wijnhaveneilands und zeigt, wie das Masterplan-Regelwerk auch unter schwierigen geometrischen Bedingungen schlanke Hochpunkte hervorbringt.

Die Position von CasaNova auf dem dicht bebauten Wijnhaveneiland macht ihn zum vorläufigen Endpunkt der untersuchten Reihe. Wo der Red Apple den Auftakt des Eilands setzte, füllt CasaNova die Kante mit einem weiteren regelkonformen Wohnturm und treibt die Verdichtung der Wohnsilhouette voran. Der Verbund mit The Muse und die gemeinsamen Dachgärten zeigen, dass das Wohnen am Wasser inzwischen nicht nur vertikal gestapelt, sondern auch um gemeinschaftliche Freiräume im Hochpunkt ergänzt wird. Damit führt der Bau die regelbasierte, schlanke Wohnbebauung des Eilands konsequent fort und markiert den gegenwärtigen Stand der Transformation.

In der hier vertretenen analytischen Lesart wird CasaNova der sechsten Erneuerungsphase Hoyles zugeordnet (Hoyle 2000); auch diese Zuordnung ist als interpretierende Setzung zu verstehen. Der Turm steht für die fortgesetzte und gegenwärtige Erneuerung der Kante, in der die Waterfront vollständig zum Wohnquartier geworden ist. Er schließt die Schichtung ab, die mit dem Witte Huis am arbeitenden Hafen begann, über das strukturalistische Wohnen der Kubuswoningen und die Büro-Wederopbouw-Kante führte und mit der regelhaften Wohn-Silhouette des Wijnhaveneilands endet. In dieser Reihe liest sich Rotterdams Umgang mit seiner Waterfront als ein Weg vom Umschlagplatz über den Rückzug bis zur planvollen Rückkehr des Wohnens an die Kante.
