= Synthese

== Eine durchgehende Linie vom Arbeitshafen zum Wohnquartier

Die vorangegangenen Einzelanalysen lassen sich zu einer durchgehenden Linie zusammenfassen, die genau jene Wandlung nachzeichnet, nach der die Leitfrage fragt. Am Anfang steht mit dem Witte Huis (1898) ein Bauwerk, das die Wasserkante noch ganz aus der Logik des Arbeitshafens denkt: ein technisch ambitionierter Hochbau am Geschäfts- und Umschlagsort, der die Adresse am Wasser als Repräsentation kaufmännischer und hafenwirtschaftlicher Macht inszeniert. In der hier vertretenen analytischen Lesart entspricht dieser Zustand der von Hoyle (1989) beschriebenen Phase der eng mit dem Hafen verzahnten, modernen Industriestadt ("modern industrial city-port"): Stadt und Hafen teilen sich dieselbe Kante, das Wasser ist Produktions- und Verkehrsraum, nicht Wohnlage.

Die zweite Schicht verschiebt diese Logik. Die Wederopbouw-Bürokante entlang der Boompjes mit der Bijbank und dem späteren EY-Turm (Boompjes 258) übersetzt die zerstörte Vorkriegsstadt in eine geordnete, von Verkehr und Verwaltung geprägte Front zum Wasser; parallel dazu setzt das strukturalistische Wohnen der Kubuswoningen (1982 bis 1984, erste Präsentation 1978) erstmals ein dezidiert städtisches Wohnprogramm an die Kante (Hengeveld 2008). In der hier vertretenen Lesart markieren beide zusammen die Schwelle zwischen Hoyles "retreat from the waterfront" und der einsetzenden "redevelopment": Der produktive Hafen zieht sich zurück, die Kante wird zur Verfügungsmasse, aber ihre künftige Bestimmung ist noch offen, zwischen Infrastrukturband und Wohnort changierend. Die dritte Schicht schließlich, mit der regelbasierten Wohnverdichtung des Red Apple (Groenendijk/Christiaanse/Brouwers 2009) und der CasaNova (2022/2023) sowie dem hybriden Wohn- und Markthallenbau der Markthal, lässt sich als jene sechste Erneuerungsphase verstehen, die Hoyle (2000) für die zeitgenössische Waterfront beschreibt: Die Kante wird programmatisch zum Wohnquartier umgewidmet, das Wasser wird Wohn- und Aufenthaltslage.

Diese Abfolge ist nicht nur chronologisch, sie ist argumentativ. Die bauliche Schichtung erzählt, dass Rotterdam seine Waterfront in keinem einzigen Akt umgewidmet hat, sondern in unterscheidbaren Etappen, von denen jede die vorhergehende sichtbar überlagert, ohne sie zu tilgen. Die Linie vom Witte Huis bis zur CasaNova ist insofern kein Bruch, sondern eine gestufte Übersetzung derselben Adresse am Wasser aus der Sprache des Hafens in die Sprache des Wohnens.

== Die Kante als ausgehandelte Grenze und als gestufte Erneuerung

Diese Linie gewinnt ihre theoretische Schärfe, wenn man sie mit Meyer (1999) als ausgehandelte Grenze zwischen Infrastruktur und Stadt liest. Meyer beschreibt die Hafenstadt nicht als Nebeneinander zweier Welten, sondern als fortlaufende Auseinandersetzung um die Kante, an der sich die Ansprüche von Verkehr, Umschlag und Hafenwirtschaft einerseits und von städtischem Leben, Wohnen und öffentlichem Raum andererseits berühren. Die Wijnhaven-Schichtung ist in dieser Perspektive die gebaute Spur dieser Aushandlung: Das Witte Huis behauptet die Kante für die Hafenökonomie, die Wederopbouw-Front ordnet sie der Verkehrs- und Verwaltungsinfrastruktur unter, und die jüngeren Wohnbauten reklamieren sie für die Stadt. An keiner Stelle ist die Grenze einfach gegeben; sie wird in jeder Schicht neu verhandelt und neu gezogen.

Mit Hoyle (1989, 2000) lässt sich derselbe Vorgang als gestufte Erneuerung beschreiben, und hier ist die phasenweise Zuordnung der Bauten ausdrücklich als die hier vertretene analytische Lesart zu verstehen, nicht als belegter Befund: Das Witte Huis verkörpert die eng verzahnte Industriestadt-Hafen-Phase, die Wederopbouw-Bürokante und die Kubuswoningen die Schwelle zwischen Rückzug und Wiederaufbau, Red Apple, Markthal und CasaNova die sechste Erneuerungsphase. Der Wert dieser Zuordnung liegt nicht in der Etikettierung, sondern darin, dass sie Meyers Aushandlungsmodell eine zeitliche Tiefe gibt. Hoyles Phasenfolge zeigt, dass die Aushandlung der Kante nicht beliebig oszilliert, sondern eine gerichtete Bewegung beschreibt, weg vom produktiven Hafen, hin zur bewohnten Waterfront.

Beide Lesarten zusammen erklären, warum die Wijnhaven heute als geschichtetes Quartier erscheint und nicht als einheitliche Komposition. Wo die Aushandlung in Etappen verläuft und jede Etappe ihre eigene bauliche Antwort hinterlässt, entsteht notwendig eine Überlagerung unterschiedlicher Maßstäbe, Typologien und Haltungen zum Wasser. Die Kante ist damit weniger ein entworfenes Bild als ein Sedimentationsprozess, in dem sich die jeweils gültige Vorstellung vom Verhältnis zwischen Hafen und Stadt ablagert.

== Das Regelwerk und die Silhouette: Folgen für Dichte und öffentlichen Raum

Die jüngste Schicht dieser Linie verdankt ihre Gestalt einem Regelwerk, nicht einem einzelnen Entwurf. Der Masterplan für das Wijnhaveneiland steuert die Verdichtung weniger über ein festes Bild als über Kennwerte und Volumenregeln, die jeden einzelnen Hochpunkt formen, ohne ihn im Detail vorzuschreiben (Lehnerer 2009; Christiaanse 2013). Maßgeblich ist eine Volumenregel, die das zulässige Bauvolumen an die Grundstücksfläche bindet; der hier zugrunde gelegte TU-Delft-Beleg nennt 22 m³/m² bei einer maximalen Turmgrundfläche von 580 m² (Mak 2011), während KCAP in eigenen Angaben teils einen höheren Wert von etwa 35 m³/m² anführt. Diese Abweichung ist transparent zu halten und nicht zu vermischen; für die Argumentation ist allein der Mechanismus entscheidend: Wer höher baut, muss schlanker bauen. Aus diesem Tauschverhältnis von Höhe gegen Schlankheit entsteht eine dichte, aber durchlässige Hochhaussilhouette, die Blickachsen zur Maas offenhält. Die für das Wijnhaveneiland genannte Dichte, ein FSI von 3,9 und im Hochbau bis 6,2 (Planangaben, die an der Primärquelle noch zu prüfen sind), deutet darauf hin, dass diese Durchlässigkeit nicht auf Kosten der Ausnutzung erkauft ist: Die Wijnhaven ist zugleich sehr dicht und visuell offen.

Für die Leitfrage ist entscheidend, dass dieses Regelwerk die Silhouette oberhalb des Straßenniveaus überzeugend ordnet, während die eigentliche Erlebnisqualität der neuen Waterfront sich nicht in der Höhe, sondern im Erdgeschoss entscheidet. Karssenberg u. a. (2016) bringen dieses Verhältnis in "The City at Eye Level" auf eine Formel: Die Sockel- oder Plinthzone macht nur etwa zehn Prozent eines Gebäudes aus, bestimmt aber rund neunzig Prozent der Erlebnisqualität auf Straßenniveau. Gehl (2010, 2011) hat die Bedeutung dieser Zone für Aufenthaltsqualität und Fußgängerleben ausführlich begründet, und Jacobs (1961) hatte mit den "eyes on the street" früh den Zusammenhang von belebten Erdgeschossen, Nutzungsmischung und Sicherheit benannt. Bemerkenswert ist, dass dieser planungstheoretische Diskurs in Rotterdam amtlich geworden ist: Die Hoogbouwvisie der Gemeente Rotterdam (2019) übernimmt ihn programmatisch, mit dem Leitbegriff "stad op ooghoogte", einem eigenen Plint-Kapitel, der Forderung nach aktiven, transparenten Sockeln und dem ausdrücklichen "afscheid van de standalone toren". Die schlanke, regelbasierte Silhouette der Wijnhaven und die Forderung nach einer lebendigen Sockelzone sind damit zwei Seiten derselben städtischen Hochhauspolitik.

Ob diese Politik an der Wijnhaven tatsächlich eingelöst wird, ist nach Lage der Quellen offen und bleibt als eigene, vor Ort zu prüfende These zu formulieren. Doucet u. a. (2011) zeigen, dass Flagship-Waterfronts häufig auf ein auswärtiges Publikum zielen und die Perspektive der Bewohner unterbelichtet bleibt, wobei sie für den nahen Kop van Zuid ein überraschend positives Bewertungsbild feststellen. Mehrere Quellen beschreiben den Straßenraum stark verdichteter Waterfronts gleichwohl als wenig belebt. Daraus ergibt sich die zentrale, hier nicht abschließend zu beantwortende Frage, ob die regelbasiert erzeugte, schlanke Wohn-Silhouette der Wijnhaven jene lebendige Sockelzone, die Rotterdams eigene Hochhauspolitik fordert, auf Straßenniveau auch wirklich herstellt, oder ob die durchlässige Silhouette ein Versprechen bleibt, das sich im Erdgeschoss noch bewähren muss.

== Beantwortung der Leitfrage

Damit lässt sich die Leitfrage verdichtet beantworten. Die Wijnhaven-Wasserkante wandelt sich zwischen 1898 und 2023 vom Arbeitshafen zum Wohnquartier nicht in einem einzigen Umbau, sondern in einer gestuften Schichtung: vom Witte Huis als Hafen-Hochbau über die Wederopbouw-Bürokante und das strukturalistische Wohnen der Kubuswoningen bis zur regelbasierten Wohnverdichtung von Red Apple und CasaNova und zum Hybrid der Markthal. Jede Schicht überlagert die vorhergehende und verschiebt zugleich die Bestimmung der Kante ein Stück weiter, weg von Produktion und Umschlag, hin zu Wohnen und öffentlichem Aufenthalt.

Was diese bauliche Schichtung über Rotterdams Umgang mit seiner Waterfront erzählt, lässt sich in einem Satz bündeln: Rotterdam behandelt seine Wasserkante weniger als fertige, einmal entworfene Form denn als regelgesteuerten, schrittweisen Übergang. Mit Meyer (1999) gelesen ist die Kante eine fortwährend ausgehandelte Grenze zwischen Infrastruktur und Stadt; mit Hoyle (1989, 2000) gelesen ist ihre Geschichte eine gerichtete, gestufte Erneuerung. Der Masterplan des Wijnhaveneiland macht diesen Umgang explizit, indem er Verdichtung nicht als Bild, sondern als Regel formuliert und so eine dichte, schlanke, für Maas-Blicke durchlässige Silhouette erzeugt (Mak 2011; Lehnerer 2009; Christiaanse 2013). Die amtliche Hochhauspolitik (Gemeente Rotterdam 2019) ergänzt diese Regel um den Anspruch einer lebendigen Sockelzone (Karssenberg u. a. 2016; Gehl 2010, 2011; Jacobs 1961), dessen tatsächliche Einlösung an der Wijnhaven offen und vor Ort zu prüfen bleibt.

Die Wijnhaven-Schichtung erweist sich so als Mikrokosmos des Rotterdamer Umgangs mit der Waterfront. In ihren übereinanderliegenden Bauphasen wird ablesbar, dass diese Stadt ihre Kante nicht als endgültiges Ergebnis versteht, sondern als einen Prozess, der über Regeln, Phasen und ausgehandelte Grenzen gesteuert wird und der, wie die offene Frage nach der Sockelzone zeigt, auch 2023 noch nicht abgeschlossen ist.
