= Fazit und Ausblick

Die Untersuchung der Wijnhaven-Wasserkante zeigt, dass sich der Wandel vom Arbeitshafen zum Wohnquartier nicht als Bruch, sondern als gestaffelte bauliche Schichtung vollzieht, in der jede Phase die vorhergehende überschreibt, ohne sie vollständig zu tilgen. Das Witte Huis (1898) markiert die Kante noch als Repräsentationsort des "modern industrial city-port" im Sinne Hoyles (Hoyle 1989), als die Verzahnung von Stadt und Hafen baulich selbstverständlich war. Die Wederopbouw und die spätere Bürokante (Bijbank, EY-Turm) sowie die Kubuswoningen (1982 bis 1984, erste Präsentation 1978) lassen sich, dies ist die hier vertretene analytische Lesart, als Schwelle zwischen "retreat from the waterfront" und "redevelopment" deuten: Der Hafenbetrieb zieht sich zurück, doch die Kante ist noch nicht als zusammenhängender Wohnort gedacht, sondern wird konzeptuell als Plan-Modell mit experimentellem Anspruch besetzt (Lehnerer 2009; Christiaanse 2013; Hengeveld 2008). Erst mit Red Apple, Markthal und CasaNova (2022/2023) erreicht die Kante jene sechste Erneuerungsphase, die Hoyle als erneute Hinwendung der Stadt zu ihrem Wasser beschreibt (Hoyle 2000), nun als verdichtete, hybride Wohn- und Versorgungslandschaft.

Was diese Schichtung über Rotterdams Umgang mit seiner Waterfront erzählt, lässt sich verdichtet so beantworten: Die Stadt behandelt die Kante nicht als Denkmalkulisse, sondern als fortlaufend beschreibbares Projektfeld, in dem Höhe, Dichte und Mischung steuerbare Parameter sind. Die Volumenregel des Masterplans, die maximal 22 m³ pro Quadratmeter Grundstücksfläche und eine maximale Turmgrundfläche von 580 m² festlegt (Mak 2011), ist dafür symptomatisch: Sie übersetzt den städtebaulichen Anspruch in eine rechnerische Regel und macht die Kante kalkulierbar. Dass KCAP teils abweichende Werte von rund 35 m³ pro Quadratmeter nennt, ist dabei nicht nebensächlich, sondern verweist auf die Differenz zwischen planerischem Anspruch und kommunizierter Kennzahl, die in einer Begehung und an Primärquellen weiter zu prüfen wäre. Die Wasserkante erscheint so als Resultat einer Planungskultur, die Wandel nicht verhindert, sondern organisiert und in baulicher Dichte sichtbar macht (Meyer 1999; Gemeente Rotterdam 2007).

Methodisch bleibt die Reichweite dieser Arbeit die einer Einzelfallstudie. Der Wijnhaven ist ein bewusst gewählter, kontextreicher Fall, dessen dichte Beschreibung exemplarische Einsichten in Rotterdams Waterfront-Logik erlaubt, nicht aber eine statistische Verallgemeinerung auf andere Städte oder Hafenkanten (Yin 2014). Gerade dieser Verzicht auf Repräsentativität ist jedoch kein Mangel, sondern produktiv: Der Einzelfall macht Mechanismen sichtbar, die ein Durchschnittsblick nivellieren würde, und korrigiert die verbreitete Annahme, kontextgebundenes Fallwissen sei wissenschaftlich nachrangig (Flyvbjerg 2006). Die hier vorgenommene Zuordnung der Bauten zu Hoyles Phasen ist entsprechend als interpretierende Lesart zu verstehen, die ein Ordnungsangebot macht und zugleich offenlegt, dass die Phasen am realen Bau ineinandergreifen und sich überlagern, statt sauber aufeinander zu folgen.

Mehrere Anschlussfragen ergeben sich, die eine Begehung vor Ort beantworten könnte und die diese Arbeit bewusst offen lässt. Erstens die Aktivierung der Sockelzone und der unmittelbaren Wasserkante: Inwieweit lösen die Erdgeschosse von Red Apple, Markthal und CasaNova den Anspruch ein, eine durchgehend belebte, fußläufig zugängliche Kante zu erzeugen, wie ihn die städtischen Programme und die Forschung zur Erdgeschossqualität formulieren (Gemeente Rotterdam 2019; Karssenberg u. a. 2016; Gehl 2010)? Eine systematische Erfassung von Nutzungsdichte, Transparenz und Aufenthaltsangeboten am Kai wäre hier der nächste empirische Schritt. Zweitens die Bewohnerperspektive: Wie erleben die heutigen Bewohnerinnen und Bewohner die verdichtete Kante, und für wen ist dieses Quartier tatsächlich zugänglich, im Anschluss an die kritische Lesart von Aufwertung und Verdrängung an Rotterdams Waterfront (Doucet u. a. 2011)? Drittens die Prüfung der hier transparent gehaltenen unsicheren Kennzahlen, von der Höhe des Witte Huis über die des EY-Turms und die divergierenden Wohnungszahlen des Red Apple bis zur Volumenregel des Masterplans, an verbindlichen Primärquellen (RCE, Rijksmonument 334003; Groenendijk/Christiaanse/Brouwers 2009). Damit bleibt die Kante, wie die Arbeit selbst, ein offenes und weiter zu beschreibendes Feld: Ihre bauliche Schichtung ist nicht abgeschlossen, sondern erzählt von einer Stadt, die ihre Waterfront immer wieder neu verhandelt.
